apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: datehash-ingress
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service: 
            name: datehash-svc
            port: 
              number: 2345
