apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifests/analysistemplate.yaml
- manifests/deployment.yaml
- manifests/service.yaml
- manifests/ingress.yaml
images:
- name: PROJECT/IMAGE
  newName: penao7/todo-frontend 
