apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifests/service-local.yaml
- manifests/ingress-local.yaml
- manifests/linkerd-deployment.yaml
images:
- name: PROJECT/IMAGE
  newName: penao7/todo-frontend-local 
