apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
  namespace: pingpongdatehash
spec:
  serviceName: postgres-svc
  replicas: 2
  selector:
    matchLabels:
      app: postgres
  template:
    metadata: 
      labels:
        app: postgres
    spec:
      containers:
        - name: postgresdb
          image: postgres
          ports:
            - name: web 
              containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: pingpong
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: data
              mountPath: /usr/app
  volumeClaimTemplates:
    - metadata:
        name: data
        namespace: pingpongdatehash
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 100Mi
