apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db
  namespace: pingpongdatehash
spec:
  encryptedData:
    postgres_password: AgASMmykYe5h1t7eFzCExlB5KCD/nmpak1k/NDHv2LfeLo1sDAUREO4mi3HLWIuFj+FDaxZvi+YdA3irXqqMmKAhZ0MK0TNxO7lx45w2lwqwEzLPvh2O7VIHdDtcbGHHj4LZy9I2bw/b9Md1aMSvQsxW1xIuk4h+0D2svqph7hGNQmwRGb3hoKm+3Q7Gn74RF1ByHwLdjI9NruFBS8n74AVSkxbfLwvRREa81gQGiNyPMgSP0igdFMTOQIUe2CE0+neHk6fNh/4sZ5OqIgH+xobhr7IOsJWHqdwVnP8R5zi+I0mGsADiMFPwTFFD1xiJz2aKthv42vaLKwcDqZOCVUtfCRf2+ffeED/CQ6wAUP3YaVlW7oUVr/RxG1dn8H85gquc/9rGpgqTnNXwMKnO6SQHO5/MuBD6tdtcdbrXPGkyp2u0U54aMtkRu1FzRaCf2uA+2JWnJpgvaf94L9fLLKHaktCQuO604OoNbFPDcZuXDXdMfByekjxHvGt8coe5Hxu6npLBx19bWyVZOfER3droBcubGOdTSi7j3UczU/s/+4uJ2me5zd2opPBRT5nb+KSQGzU1ZkwsmCmZR+j4xK0HUa+VkHvpo9Re01mW8FOghoHvJRzVDqf52fjbqRcS84nAvGw2fQlbCkJo+SYvutOjQmdwQep1kbciEW8qtl4qukNIVNI+IHNPoNqlPBmGU7yr2JTfQ5bmkCO21Ks=
  template:
    metadata:
      creationTimestamp: null
      name: db
      namespace: pingpongdatehash

