apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-graphql
  namespace: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-graphql
  template:
    metadata:
      labels:
        app: todo-graphql
    spec:
      containers:
        - name: graphql
          image: penao7/todo-graphql
          ports:
            - containerPort: 4000
          env:
            - name: NODE_ENV
              value: production
            - name: TODO_USER_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-pw
                  key: TODO_USERNAME
            - name: TODO_USER_PASSWORD 
              valueFrom:
                secretKeyRef:
                  name: mongodb-pw
                  key: TODO_PASSWORD
            - name: NATS_URL
              value: nats://my-nats:4222
          livenessProbe:
            httpGet:
              path: /.well-known/apollo/server-health
              port: 4000
            initialDelaySeconds: 15
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /.well-known/apollo/server-health
              port: 4000
            initialDelaySeconds: 5
            periodSeconds: 10
