apiVersion: v1
kind: Service
metadata: 
  name: todo-graphql
  namespace: todo-app
spec:
  type: NodePort 
  selector:
    app: todo-graphql
  ports:
    - name: http
      protocol: TCP
      port: 4000 
      targetPort: 4000 
