apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: todo-app
  name: mongodb
spec:
  serviceName: mongo-svc
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      volumes:
        - name: mongo-initdb
          configMap:
            name: mongo-initdb
      containers:
        - name: mongo
          image: mongo:4.2.10
          ports:
            - name: web
              containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: root
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-pw
                  key: ROOT_PASSWORD
            - name: TODO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-pw
                  key: TODO_USERNAME
            - name: TODO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-pw
                  key: TODO_PASSWORD
          volumeMounts:
            - name: mongo-initdb
              mountPath: /docker-entrypoint-initdb.d
            - name: data
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: data
        namespace: todo-app
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 100Mi
