name: Delete environment

on:
  delete:

env:
  GKE_CLUSTER: dwk-cluster
  GKE_ZONE: europe-north1-b

jobs:
  delete-environment:
    name: Delete environment
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: google-github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        project_id: ${{ secrets.GKE_PROJECT_ID }}

    - run: gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"

    - name: delete namespace
      run: |
        GITHUB_EVENT_REF=$(echo ${{ github.event.ref }} | sed -e "s#refs/heads/##g")
        kubectl delete namespace $GITHUB_EVENT_REF

