apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifests/serviceaccount.yaml
- manifests/clusterrole.yaml
- manifests/clusterrolebinding.yaml
- manifests/deployment.yaml
