apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-dailyimage
  namespace: todo-app 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-dailyimage
  template:
    metadata:
      labels:
        app: todo-dailyimage
    spec:
      volumes:
        - name: dailyimage
          persistentVolumeClaim:
            claimName: dailyimage-claim
      containers:
        - name: dailyimage
          image: PROJECT/IMAGE 
          ports:
          - containerPort: 8000
          volumeMounts:
          - name: dailyimage
            mountPath: /usr/app
          resources:
            limits:
              cpu: "150m"
              memory: "100Mi"
          livenessProbe:
            initialDelaySeconds: 20
            periodSeconds: 5
            httpGet:
              path: /dailyimage
              port: 8000
          readinessProbe:
            initialDelaySeconds: 20
            periodSeconds: 5
            httpGet:
              path: /dailyimage
              port: 8000



