apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: dailyimage-hpa
  name: todo-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: todo-dailyimage
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50
