apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: todo-claim
  namespace: todo-app
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
