apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dailyimage-claim
  namespace: todo-app
spec:
  # storageClassName: manual # UNCOMMENT FOR LOCAL TESTING
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
