apiVersion: v1
kind: Service
metadata: 
  name: todo-dailyimage
  namespace: todo-app
spec:
  selector:
    app: todo-dailyimage
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000 
