apiVersion: v1
kind: Service
metadata: 
  name: todo-backend
  namespace: todo-app
spec:
  type: ClusterIP
  selector:
    app: todo-backend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000 
