apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: scraper-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: scraper-controller-role
subjects:
- kind: ServiceAccount
  name: scraper-controller-account
  namespace: default
