apiVersion: apps/v1
kind: Deployment
metadata:
  name: scraper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scraper
  template:
    metadata:
      labels:
        app: scraper
    spec:
      serviceAccountName: scraper-controller-account
      containers:
        - name: scraper
          image: penao7/scraper
