apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifests/pvc.yaml
- manifests/service.yaml
- manifests/deployment.yaml
images:
- name: PROJECT/IMAGE
  newName: penao7/todo-dailyimage
