apiVersion: apps/v1
kind: Deployment
metadata:
  name: random-string-generator-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: random-string-generator 
  template:
    metadata:
      labels:
        app: random-string-generator 
    spec:
      containers:
        - name: random-string-generator
          image: penao7/random_string_app:v0.3 
