apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: bot-token
  namespace: todo-app
spec:
  encryptedData:
    BOT_TOKEN: AgCuErE1IQa75+vIkWexOLyguW+etEy2tRU4q8gNLF/GMM75dQtZFGQzGHt6kBLhWHTiikKJcagc80TLgNywYDFxvadL11O2AB4TzqDYgYCR8nJ1JYtSUChL9Im7M6c7g5mIODoiatxL9qGHiKJF0mBcfOVPhdd4FZdchm/iZsDA4EP0vZJf5PBw/YEBQ+U4lkfoYvysU98lcQZqQYs1y4uYjWLdrNmu5iU9pUh4l476RRzuqkj1TuYAQIMy7bIowkQnU8EbcBeHR56zGs+4kru8EsrMi93NxPx9ryz2ooncAQj2ADT1b/aypFjJzGW/gNJXjx7cZ8XRxOi7hMAiHhNmNC7NiofJAdMdLYWE3KfzTLHPdlfRoTc3Edn0OnRT8nlvXX7uBE/7w3y/XMD0XCyJF8ngX+6lYZDNhpzt4b1CPaYOciydf0a9IzhkxV0biEX+lMnYI2wTpaH2yYKKIpMX2EBw7EmENvoAcWGAIoXyMFtC8YDJTKDcXxkhKYihKFSlm8io0fN47Smn9FKklm7jxbddd0KNGcPtWu8SFIxzWtHr4i9A4rTrRF9Tu+koB71sZFz4vnJxE/IGnzy9zgvQSQymAaL+jSFb7b3iybgr1swY2JAP6xaki0XWG0nCuNWudEVCPgJzt0CZWkcQ/VNXCSqQ5xl0l6UM+O3T/rDpHpPm2q9Jk7PMWSPF1tGKXfd0//xgvwiT6PCUiswBHcabFrHVlhF/RjoMzdgHlmIP/aBmx2Ir4S6WNVsatspd
    CHATROOM: AgCJgQI6VUAa/F+bwMuUqN0BJ4KYtxHjlkKCVSymD86qdchpSJQ7LsF7ugXUyVjgQpmwcfKIcOaFVNUyosdh4smUD3lQnXruSXLjURHTrPS/Zd/VFJL/GFc0cLzdm/UF+FBDtE++oSBdg/BywMsFShoFkbT+HhTh+2B2JFfk05wa88EWMiO1M18MMsrV++8OAT7+XLFtoAboVrKMoZuG54/BUyadtEOURyXMU0XYAZMFebCko4RwQf+27/2MPiJAntdLbNlcG4JdqDgx7Od1q3w6QSekTTzpESj8X51RUzGRoo3tWaANtGnLl5tWcNGVHtrkKMCJB5/y546ayer2XfJhgZSMDI1Wz3KWVr2wPZPvPEzvpAP0gLeSAAuOGpDDHtGBh6jwsOqUvd07CNXPPPLx+V+znWL4md/jqy+4fNE37eY4iUUI1PpaN3ciuh3usF/tpEQ+rCDPnN75zT6JwB7WKBThCYUulbYuS+oEldIsW598Pfn9Kd+cW9ALw0Lk9GTZj+5pVk9zPyrcuOcsLa+TGZpZpe45YWItbkxv+0oZ8LUSBNp/dIUchBn2PWC7qrUkZdukFdKu2vL5sHnTJR1vbjNDMfLTijPvkQ7GV/r0skGz2ny8/7SUopaBJzGPYtXUh069l8LPsJb1+EaCQ9GUNcJPJjqUg6earTjPynG9Y3wzla7RNMFHM9ddAqg2ZaNaYt3mX6yTqswJ
  template:
    metadata:
      creationTimestamp: null
      name: bot-token
      namespace: todo-app

