apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingpong
  namespace: pingpongdatehash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingpong
  template:
    metadata:
      labels:
        app: pingpong
    spec:
      containers:
        - name: pingpong
          image: penao7/pingpong
          ports:
          - containerPort: 4000 
          resources:
            limits:
              cpu: "50m"
              memory: "50Mi"
          env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: POSTGRES_PASSWORD
          readinessProbe:
            httpGet:
              path: /
              port: 4000
            initialDelaySeconds: 5
            periodSeconds: 5
          volumeMounts:
            - name: db-secret
              mountPath: "/etc/secrets"
              readOnly: true
      volumes:
        - name: db-secret
          secret:
            secretName: db-secret



