apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: pingpong
  namespace: pingpongdatehash
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pingpong-dep
  minReplicas: 1
  maxReplicas: 6
  targetCPUUtilizationPercentage: 50
