apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: pingpong-app
spec:
  template:
    metadata:
      name: pingpong-app-dwk-v1
    spec:
      containers:
        - image: penao7/pingpong
          env:
            name: APP_PORT
            value: 8080
          volumeMounts:
            - name: db-secret
              mountPath: "/etc/secrets"
              readOnly: true
      volumes:
        - name: db-secret
          secret:
            secretName: db-secret

