apiVersion: v1
kind: Service
metadata:
  name: pingpong
  namespace: pingpongdatehash
spec:
  type: ClusterIP
  selector:
    app: pingpong 
  ports:
    - port: 1234
      protocol: TCP
      targetPort: 4000
