apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: pingpong-app
spec:
  template:
    metadata:
      name: pingpong-app-dwk-v5
    spec:
      containers:
        - image: penao7/pingpong
          ports:
            - containerPort: 8081
          volumeMounts:
            - name: db-secret
              mountPath: "/etc/secrets"
              readOnly: true
      volumes:
        - name: db-secret
          secret:
            secretName: db-secret

