apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: cpu-usage
  namespace: todo-app
spec:
  metrics:
  - name: cpu-usage
    initialDelay: 10m
    successCondition: result < 0.5
    provider:
      prometheus:
        address: http://kube-prometheus-stack-1610-prometheus.prometheus.svc.cluster.local:9090
        query: |
          scalar(namespace:container_cpu_usage_seconds_total:sum_rate{namespace="todo-app"} offset 10m) 
