apiVersion: networking.k8s.io/v1beta1 
kind: Ingress
metadata:
  name: todo-ingress
  namespace: todo-app
  annotations:
    kubernetes.io/ingress.global-static-ip-name: todo-app-ip
spec:
  rules:
  - http:
      paths:
      - path: /*
        backend:
          serviceName: todo-frontend
          servicePort: 8000
      - path: /api
        backend:
          serviceName: todo-graphql
          servicePort: 4000
