apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: randomwikitodo
  namespace: todo-app
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: randomwikitodo
            image: penao7/randomwikitodo
          restartPolicy: OnFailure
