apiVersion: apps/v1
kind: Deployment
metadata:
  name: datehash-dep
  namespace: pingpongdatehash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: datehash
  template:
    metadata:
      labels:
        app: datehash
    spec:
      volumes:
        - name: datelog
          persistentVolumeClaim:
            claimName: pingpongdate-claim
      containers:
        - name: date
          image: penao7/date
          volumeMounts:
          - name: datelog
            mountPath: /usr/app/
          resources:
            limits:
              cpu: "150m"
              memory: "100Mi"
        - name: hash
          image: penao7/hash
          env:
            - name: MESSAGE 
              valueFrom:
                configMapKeyRef:
                  name: hello-configmap
                  key: MESSAGE
          ports:
          - containerPort: 3500
          resources:
            limits:
              cpu: "150m"
              memory: "100Mi"
          volumeMounts:
          - name: datelog
            mountPath: /usr/app/
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            exec:
              command:
                - "wget"
                - "-qO-"
                - "pingpong"
