apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: datehash-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: datehash-dep
  minReplicas: 1
  maxReplicas: 6
  targetCPUUtilizationPercentage: 50
